version: "3.2"

services:
  dev:
    container_name: node-subtensor
    image: paritytech/ci-linux:production
    working_dir: /var/www/node-subtensor
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
      - WASM_BUILD_TOOLCHAIN=nightly-2020-10-05
    volumes:
      - .:/var/www/node-subtensor
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/node-subtensor --dev --ws-external"
